import hashlib
import json
import mimetypes
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, Optional

from .config import RepoPaths, build_paths


def now_utc() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def slugify(value: str) -> str:
    lowered = value.strip().lower()
    lowered = re.sub(r"[^a-z0-9]+", "-", lowered)
    lowered = re.sub(r"-{2,}", "-", lowered).strip("-")
    return lowered or "item"


def ensure_repo_structure(root: Path) -> RepoPaths:
    paths = build_paths(root)
    for directory in (
        paths.config_dir,
        paths.raw_inbox,
        paths.raw_archive,
        paths.source_manifests,
        paths.artifact_manifests,
        paths.records,
        paths.briefs,
        paths.timeline_context,
        paths.interventions_context,
        paths.data_index,
        paths.schemas,
        paths.docs,
        paths.skills,
    ):
        directory.mkdir(parents=True, exist_ok=True)
    keep = paths.raw_archive / ".gitkeep"
    if not keep.exists():
        keep.write_text("", encoding="utf-8")
    _write_json_default(paths.google_calendar_config_path, _default_google_calendar_config(root))
    _write_json_default(paths.morning_light_config_path, _default_morning_light_config())
    _write_json_default(paths.weather_evidence_registry_path, _default_weather_evidence_registry())
    _write_json_default(paths.weather_susceptibility_path, _default_weather_susceptibility())
    return paths


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def read_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def load_json_if_exists(path: Path, default: Optional[Any] = None) -> Any:
    if not path.exists():
        return default
    return read_json(path)


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def sha256sum(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def guess_mime_type(path: Path) -> str:
    mime, _ = mimetypes.guess_type(str(path))
    return mime or "application/octet-stream"


def archive_artifact(path: Path, paths: RepoPaths, source_type: str, checksum: str) -> Path:
    target_dir = paths.raw_archive / source_type / checksum[:8]
    target_dir.mkdir(parents=True, exist_ok=True)
    target_path = target_dir / path.name
    if not target_path.exists():
        shutil.copy2(path, target_path)
    return target_path


def discover_input_files(path: Path) -> Iterable[Path]:
    if path.is_file():
        return [path]
    return sorted(
        candidate
        for candidate in path.rglob("*")
        if candidate.is_file() and not candidate.name.endswith(".meta.json")
    )


def _write_json_default(path: Path, payload: Any) -> None:
    if path.exists():
        return
    write_json(path, payload)


def _default_google_calendar_config(root: Path) -> Dict[str, Any]:
    return {
        "workspace_name": root.name,
        "google_client_id_env": "OPENHEALTH_GOOGLE_CLIENT_ID",
        "google_client_secret_env": "OPENHEALTH_GOOGLE_CLIENT_SECRET",
        "google_redirect_uri_env": "OPENHEALTH_GOOGLE_REDIRECT_URI",
        "selected_calendar_ids": [],
        "derived_calendar": {
            "name": "OpenHealth Derived",
            "id": None,
            "description": "Derived hypothetical circadian and weather events generated by OpenHealth.",
        },
        "timezone": "Asia/Tbilisi",
        "home_location": {
            "label": "Tbilisi",
            "latitude": 41.7151,
            "longitude": 44.8271,
        },
        "writeback": {
            "enabled": True,
            "read_source_calendars_only": True,
        },
    }


def _default_morning_light_config() -> Dict[str, Any]:
    return {
        "mode": "manual+automation-hook",
        "default_minutes": 15,
        "notes": "Manual morning light check-ins are the MVP. Siri Shortcuts or iPhone automation can post into the same contract later.",
        "automation_hook": {
            "enabled": False,
            "contract": "Record a morning-light observation with timestamp, duration_minutes, source, and optional location.",
        },
    }


def _default_weather_evidence_registry() -> Dict[str, Any]:
    return {
        "version": 1,
        "factors": [
            {
                "factor": "low_relative_humidity",
                "affected_domains": ["dry_eyes", "dry_skin", "airway_irritation"],
                "populations": ["people with dryness sensitivity", "people with ocular surface sensitivity"],
                "evidence_strength": "mixed",
                "general_note": "Dry air can aggravate dryness-related complaints, but effects vary a lot across people and settings.",
            },
            {
                "factor": "barometric_pressure_change",
                "affected_domains": ["migraine", "headache"],
                "populations": ["people with weather-sensitive headaches"],
                "evidence_strength": "mixed",
                "general_note": "Weather-linked headache and migraine reports exist, but prediction quality is person-specific.",
            },
            {
                "factor": "heat_load",
                "affected_domains": ["fatigue", "sleep_disruption", "heat_intolerance"],
                "populations": ["people with poor heat tolerance", "people under high activity load"],
                "evidence_strength": "supported",
                "general_note": "Heat can meaningfully raise perceived exertion and impair comfort or sleep.",
            },
            {
                "factor": "cold_exposure",
                "affected_domains": ["joint_pain", "stiffness"],
                "populations": ["people who self-report cold sensitivity"],
                "evidence_strength": "insufficient",
                "general_note": "General evidence is inconsistent, so cold-related impact should be treated as a personal hypothesis unless reinforced by personal data.",
            },
            {
                "factor": "high_wind",
                "affected_domains": ["dry_eyes", "skin_irritation"],
                "populations": ["people with ocular or skin sensitivity"],
                "evidence_strength": "mixed",
                "general_note": "Wind can amplify discomfort through evaporation and exposure, but not everyone is affected.",
            },
        ],
    }


def _default_weather_susceptibility() -> Dict[str, Any]:
    return {
        "declared_sensitivities": [],
        "personally_supported_signals": [],
        "suppression_note": "If no sensitivity is declared or supported, OpenHealth should suppress confident weather claims.",
    }
