"""Genotype ingestion tests for the dashboard DNA block.

Covers both raw formats the block accepts — a 23andMe-style export and a
single-sample VCF (what array/WGS labs such as Genotek hand back) — and locks
in that equivalent inputs yield identical curated calls.

All fixtures are synthetic: invented genotypes at real rsid coordinates, never
anyone's actual data.
"""

import importlib.util
import json
import sqlite3
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
_MODULE_PATH = REPO_ROOT / "ui" / "web" / "build_dashboard_data.py"
_spec = importlib.util.spec_from_file_location("build_dashboard_data_dna", _MODULE_PATH)
bdd = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(bdd)

# rs762551 CYP1A2, rs4988235 MCM6/LCT, rs1815739 ACTN3 — all in _DNA_SPEC.
TWENTY_THREE_AND_ME = (
    "# This data file generated by a test\n"
    "# rsid\tchromosome\tposition\tgenotype\n"
    "rs762551\t15\t75041917\tAA\n"
    "rs4988235\t2\t136608646\tGG\n"
    "rs1815739\t11\t66328095\tTC\n"
)

# Same three calls expressed as a VCF: REF/ALT + GT must decode to the bases above.
VCF = (
    "##fileformat=VCFv4.2\n"
    "##reference=hg19\n"
    "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tsample1\n"
    "chr15\t75041917\trs762551\tC\tA\t.\t.\t.\tGT\t1/1\n"        # ALT/ALT -> AA
    "chr2\t136608646\trs4988235\tG\tA,C\t.\t.\t.\tGT\t0/0\n"     # REF/REF, multi-allelic -> GG
    "chr11\t66328095\trs1815739\tT\tC\t.\t.\t.\tGT\t0/1\n"       # REF/ALT -> TC
)


def _con_with_genotype(path: Path) -> sqlite3.Connection:
    con = sqlite3.connect(":memory:")
    con.execute("CREATE TABLE sources (source_id TEXT PRIMARY KEY, payload_json TEXT NOT NULL)")
    con.execute(
        "INSERT INTO sources VALUES (?, ?)",
        ("genotype-test", json.dumps({"files": [str(path)]})),
    )
    return con


def _calls(text: str, suffix: str) -> dict:
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / ("genotype" + suffix)
        path.write_text(text, encoding="utf-8")
        con = _con_with_genotype(path)
        try:
            return {v["rsid"]: v["genotype"] for v in bdd.build_dna(con)}
        finally:
            con.close()


class TestGenotypeFormats(unittest.TestCase):
    def test_23andme_export_is_parsed(self):
        self.assertEqual(
            _calls(TWENTY_THREE_AND_ME, ".txt"),
            {"rs762551": "AA", "rs4988235": "GG", "rs1815739": "TC"},
        )

    def test_vcf_decodes_to_the_same_calls(self):
        """A VCF and an equivalent 23andMe export must agree — the whole point."""
        self.assertEqual(_calls(VCF, ".vcf"), _calls(TWENTY_THREE_AND_ME, ".txt"))

    def test_vcf_phased_genotype_separator(self):
        vcf = VCF.replace("\tGT\t0/1", "\tGT\t0|1")
        self.assertEqual(_calls(vcf, ".vcf")["rs1815739"], "TC")

    def test_vcf_skips_no_calls(self):
        vcf = VCF.replace("\tGT\t1/1", "\tGT\t./.")
        calls = _calls(vcf, ".vcf")
        self.assertNotIn("rs762551", calls)
        self.assertIn("rs1815739", calls)  # other rows still land

    def test_vcf_skips_non_snv(self):
        """Indels can't be expressed as a two-base call; the curated set is SNVs."""
        vcf = VCF.replace("chr11\t66328095\trs1815739\tT\tC", "chr11\t66328095\trs1815739\tT\tTCA")
        self.assertNotIn("rs1815739", _calls(vcf, ".vcf"))

    def test_vcf_surfaces_curated_note_and_grade(self):
        """Format is only the input side — curated interpretation still applies."""
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "g.vcf"
            path.write_text(VCF, encoding="utf-8")
            con = _con_with_genotype(path)
            try:
                by_rsid = {v["rsid"]: v for v in bdd.build_dna(con)}
            finally:
                con.close()
        cyp = by_rsid["rs762551"]
        self.assertEqual(cyp["gene"], "CYP1A2")
        self.assertEqual(cyp["grade"], "C3")
        self.assertTrue(cyp["note"])

    def test_missing_source_yields_nothing(self):
        con = sqlite3.connect(":memory:")
        con.execute("CREATE TABLE sources (source_id TEXT PRIMARY KEY, payload_json TEXT NOT NULL)")
        try:
            self.assertEqual(bdd.build_dna(con), [])
        finally:
            con.close()


if __name__ == "__main__":
    unittest.main()
