#!/usr/bin/env python3
"""Build OpenHealth.app — a minimal macOS desktop app for the local dashboard.

WHY
---
OpenHealth is local-first: a stdlib Python server (`server.py`) + web UI. The
missing piece for "feels like a product" is a double-clickable app: today the
user must remember to start the server in a terminal and open the URL. This
script builds a native .app bundle whose launcher does exactly that:

  1. if nothing is listening on the port, start `server.py` (loading WHOOP env
     from ~/health-os/.env.whoop.local when present) and wait until it answers;
  2. open the dashboard as an app-mode window (Chrome `--app=`) so it gets its
     own Dock icon and no browser chrome; falls back to the default browser.

Pure stdlib + built-in macOS tools (qlmanage/sips/iconutil for the icon; the
icon step degrades gracefully if any of them is missing). No Electron, no
dependencies, fully local — matches the project's core rules.

Usage (from repo root or ui/web):
    python3 ui/web/make_macos_app.py              # build ui/web/dist/OpenHealth.app
    python3 ui/web/make_macos_app.py --install    # also copy to ~/Applications
    python3 ui/web/make_macos_app.py --port 8770  # custom port (default 8770)

Note: the launcher bakes in the absolute path of this checkout. If you move the
repo, re-run this script.
"""
from __future__ import annotations

import argparse
import plistlib
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent          # ui/web
APP_NAME = "OpenHealth"
BUNDLE_ID = "org.openhealth.local"

LAUNCHER = """#!/bin/bash
# OpenHealth.app launcher — generated by make_macos_app.py (do not edit by hand).
# Starts the local server if needed, then opens the dashboard as an app window.
set -u
REPO="{repo}"
PORT={port}
URL="http://localhost:$PORT/"
LOG="$HOME/Library/Logs/OpenHealth.log"

port_up() {{ curl -s -o /dev/null --max-time 1 "$URL"; }}

find_python() {{
  for p in /opt/homebrew/bin/python3 /usr/local/bin/python3 /usr/bin/python3; do
    [ -x "$p" ] && echo "$p" && return 0
  done
  command -v python3
}}

if ! port_up; then
  PY="$(find_python)"
  if [ -z "$PY" ]; then
    osascript -e 'display alert "OpenHealth" message "python3 не найден. Установи Xcode Command Line Tools (xcode-select --install) и открой приложение снова."'
    exit 1
  fi
  # WHOOP credentials for the Sync button (optional; local file, never bundled).
  ENVF="$HOME/health-os/.env.whoop.local"
  if [ -f "$ENVF" ]; then set -a; . "$ENVF"; set +a; fi
  mkdir -p "$(dirname "$LOG")"
  (cd "$REPO" && nohup "$PY" server.py --port "$PORT" --dir . >> "$LOG" 2>&1 &)
  for _ in $(seq 1 50); do port_up && break; sleep 0.2; done
fi

if ! port_up; then
  osascript -e 'display alert "OpenHealth" message "Сервер не поднялся. Лог: ~/Library/Logs/OpenHealth.log"'
  exit 1
fi

# App-mode window (own Dock entry, no browser chrome) when Chrome exists;
# otherwise the default browser. Both land on the skin router (index.html).
if [ -d "/Applications/Google Chrome.app" ]; then
  open -na "Google Chrome" --args --app="$URL"
else
  open "$URL"
fi
"""


def build_icns(out_dir: Path) -> str | None:
    """Render assets/icon.svg into AppIcon.icns via qlmanage → sips → iconutil.

    Returns the icns file name, or None when any tool is unavailable (the app
    then simply uses the generic icon — build still succeeds).
    """
    svg = HERE / "assets" / "icon.svg"
    if not svg.is_file():
        return None
    for tool in ("qlmanage", "sips", "iconutil"):
        if shutil.which(tool) is None:
            return None
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td)
        # qlmanage renders SVG to <name>.svg.png
        subprocess.run(
            ["qlmanage", "-t", "-s", "1024", "-o", str(tmp), str(svg)],
            capture_output=True, check=False,
        )
        base = tmp / (svg.name + ".png")
        if not base.is_file():
            return None
        iconset = tmp / "AppIcon.iconset"
        iconset.mkdir()
        for size in (16, 32, 64, 128, 256, 512, 1024):
            for scale, suffix in ((1, ""), (2, "@2x")):
                px = size * scale
                if px > 1024:
                    continue
                name = "icon_%dx%d%s.png" % (size, size, suffix)
                subprocess.run(
                    ["sips", "-z", str(px), str(px), str(base),
                     "--out", str(iconset / name)],
                    capture_output=True, check=False,
                )
        icns = out_dir / "AppIcon.icns"
        res = subprocess.run(
            ["iconutil", "-c", "icns", str(iconset), "-o", str(icns)],
            capture_output=True, check=False,
        )
        return "AppIcon.icns" if res.returncode == 0 and icns.is_file() else None


def build_app(dist: Path, port: int) -> Path:
    app = dist / (APP_NAME + ".app")
    if app.exists():
        shutil.rmtree(app)
    macos = app / "Contents" / "MacOS"
    resources = app / "Contents" / "Resources"
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    launcher = macos / APP_NAME
    launcher.write_text(LAUNCHER.format(repo=str(HERE), port=port), encoding="utf-8")
    launcher.chmod(0o755)

    icns_name = build_icns(resources)

    info: dict = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleVersion": "1.0",
        "CFBundleShortVersionString": "1.0",
        "CFBundlePackageType": "APPL",
        "CFBundleExecutable": APP_NAME,
        "LSMinimumSystemVersion": "11.0",
        # The launcher exits after opening the window; no lingering ghost app.
        "LSBackgroundOnly": False,
    }
    if icns_name:
        info["CFBundleIconFile"] = icns_name
    with (app / "Contents" / "Info.plist").open("wb") as fh:
        plistlib.dump(info, fh)
    return app


def main(argv) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--port", type=int, default=8770)
    ap.add_argument("--install", action="store_true",
                    help="copy the built app into ~/Applications")
    args = ap.parse_args(argv)

    if sys.platform != "darwin":
        print("make_macos_app.py: macOS only", file=sys.stderr)
        return 1

    dist = HERE / "dist"
    dist.mkdir(exist_ok=True)
    app = build_app(dist, args.port)
    print("built: %s" % app)

    if args.install:
        target_dir = Path.home() / "Applications"
        target_dir.mkdir(exist_ok=True)
        target = target_dir / app.name
        if target.exists():
            shutil.rmtree(target)
        shutil.copytree(app, target, symlinks=True)
        print("installed: %s" % target)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
